const fs = require('fs');
const lines = fs.readFileSync('server.js', 'utf8').split('\n');

const newLines = [
  ...lines.slice(0, 194),
  '// Login',
  "app.post('/api/login', async (req, res) => {",
  '  try {',
  '    const { email, password } = req.body;',
  '    const user = await User.findOne({ email, password });',
  '    if (user) {',
  '      if (user.twoFactorEnabled) {',
  '        return res.json({ requires2FA: true, userId: user._id });',
  '      }',
  '      res.json({ id: user._id, name: user.name, role: user.role, email: user.email });',
  '    } else {',
  "      res.status(401).json({ error: 'Invalid credentials' });",
  '    }',
  '  } catch (error) {',
  '    res.status(500).json({ error: error.message });',
  '  }',
  '});',
  '',
  '// Verify 2FA at Login',
  "app.post('/api/login/2fa', async (req, res) => {",
  '  try {',
  '    const { userId, token } = req.body;',
  '    const user = await User.findById(userId);',
  '    if (!user) return res.status(404).json({ error: "User not found" });',
  "    const speakeasy = require('speakeasy');",
  "    const verified = speakeasy.totp.verify({ secret: user.twoFactorSecret, encoding: 'base32', token: token, window: 1 });",
  '    if (verified) {',
  '      res.json({ id: user._id, name: user.name, role: user.role, email: user.email });',
  '    } else {',
  '      res.status(401).json({ error: "Invalid 2FA code" });',
  '    }',
  '  } catch (error) {',
  '    res.status(500).json({ error: error.message });',
  '  }',
  '});',
  '',
  '// Setup 2FA',
  "app.post('/api/users/:id/2fa/setup', async (req, res) => {",
  '  try {',
  '    const user = await User.findById(req.params.id);',
  '    if (!user) return res.status(404).json({ error: "User not found" });',
  "    const speakeasy = require('speakeasy');",
  "    const qrcode = require('qrcode');",
  '    const secret = speakeasy.generateSecret({ name: `IntelliTasker (${user.email})` });',
  '    user.twoFactorSecret = secret.base32;',
  '    await user.save();',
  '    qrcode.toDataURL(secret.otpauth_url, (err, data_url) => {',
  '      if (err) throw err;',
  '      res.json({ secret: secret.base32, qrCode: data_url });',
  '    });',
  '  } catch (error) {',
  '    res.status(500).json({ error: error.message });',
  '  }',
  '});',
  '',
  '// Verify and Enable 2FA',
  "app.post('/api/users/:id/2fa/verify', async (req, res) => {",
  '  try {',
  '    const { token } = req.body;',
  '    const user = await User.findById(req.params.id);',
  '    if (!user) return res.status(404).json({ error: "User not found" });',
  "    const speakeasy = require('speakeasy');",
  "    const verified = speakeasy.totp.verify({ secret: user.twoFactorSecret, encoding: 'base32', token: token, window: 1 });",
  '    if (verified) {',
  '      user.twoFactorEnabled = true;',
  '      await user.save();',
  '      res.json({ success: true });',
  '    } else {',
  '      res.status(400).json({ error: "Invalid code" });',
  '    }',
  '  } catch (error) {',
  '    res.status(500).json({ error: error.message });',
  '  }',
  '});',
  ...lines.slice(205)
];
fs.writeFileSync('server.js', newLines.join('\n'));
console.log('Fixed server.js 2fa routes');
